from app.models.usuario import Usuario
from app.models.rol import Rol
from app.models.usuario_rol import usuario_roles
from app.models.carrera import Carrera
from app.models.cuatrimestre import Cuatrimestre
from app.models.materia import Materia
from app.models.materia_prerrequisito import MateriaPrerrequisito
from app.models.plan_estudio import PlanEstudio
from app.models.plan_materia import PlanMateria
from app.models.alumno import Alumno
from app.models.procedencia_academica import ProcedenciaAcademica
from app.models.tutor import Tutor
from app.models.alumno_tutor import alumno_tutor
from app.models.contacto_emergencia import ContactoEmergencia
from app.models.seguro_medico import SeguroMedico
from app.models.docente import Docente
from app.models.periodo import Periodo
from app.models.grupo import Grupo
from app.models.grupo_materia import GrupoMateria
from app.models.inscripcion import Inscripcion
from app.models.carga_academica import CargaAcademica
from app.models.parcial import Parcial
from app.models.calificacion import Calificacion
from app.models.extraordinario import Extraordinario
from app.models.historial_academico import HistorialAcademico
from app.models.asistencia import Asistencia
from app.models.tipo_documento import TipoDocumento
from app.models.documento_alumno import DocumentoAlumno
from app.models.recepcion_documento import RecepcionDocumento
from app.models.empresa import Empresa
from app.models.servicio_social import ServicioSocial
from app.models.practica_profesional import PracticaProfesional
from app.models.titulacion import Titulacion
